runtime: nodejs10
handlers:
  - url: /(.*\.(js|css|png|ico|txt|svg))$
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|ico|txt|svg)$
  - url: .*
    static_files: dist/index.html
    upload: dist/index.html