runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /(.*\.(js|css|png|ico|txt))$
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|ico|txt)$
  - url: .*
    static_files: dist/index.html
    upload: dist/index.html